@HotelListing.Api_HostAddress = https://localhost:7215
@json = application/json
@basicAuth = dXNlcjFAbG9jYWxob3N0LmNvbTpQYXNzd29yZDEh
@apiKey = dXNlcjFAbG9jYWxob3N0LmNvbTpQYXNzd29yZDEh
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWQwM2ZkNC0zYTY3LTQ4NGQtYjBkNC1mMTYwYjNjODY5MzIiLCJlbWFpbCI6InVzZXIyQGxvY2FsaG9zdC5jb20iLCJqdGkiOiIzNmYyOGQ3My1hZDllLTQ3ZTgtOGM0NC0zYjg5ZGE0N2U2MjAiLCJuYW1lIjoiSm9obiBEb2UiLCJleHAiOjE3NzA2MzUzNTUsImlzcyI6IkhvdGVsTGlzdGluZ0FwaSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.-6fxhK8ZUnJC_aIG6-2bNo-rawj1tXkw9IRawu5A33M
@bearerToken2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZGZjNDlkNy1kNjJhLTQ1M2ItOGRjZC1jOTBmMTVkY2NiNTYiLCJlbWFpbCI6InVzZXJAbG9jYWxob3N0LmNvbSIsImp0aSI6ImQyNjQ4NTFlLTFhZjQtNDc0YS1iMGVlLTA3NjIxYjk2OGY2ZiIsIm5hbWUiOiIgIiwiZXhwIjoxNzcwNjQzMDUwLCJpc3MiOiJIb3RlbExpc3RpbmdBcGkiLCJhdWQiOiJIb3RlbExpc3RpbmdBUElDbGllbnQifQ.7ZYDijRVCWK9YghA3MsM6IjylL694Na1lGeoV3J-g20
@id=1
GET {{HotelListing.Api_HostAddress}}/api/countries
#X-Api-Key: {{apiKey}}
#Authorization: Basic {{basicAuth}}
Authorization: Bearer {{bearerToken2}}
###

POST {{HotelListing.Api_HostAddress}}/api/countries
Authorization: Bearer {{bearerToken2}}

{
  "name": "Test Admin Country",
  "shortName": "TAC"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Authorization: Bearer {{bearerToken2}}

###

GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: {{json}}

{
  "countryId": 2,
  "name": "Jamaica",
  "shortName": "JM"
}
###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: {{json}}

{
  "Id":4,
  "Name": "Moon Palace",
  "Address": "Ocho str",
  "Rating": 4,
  "CountryId": 3
}

###
@id=4
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: {{json}}

{
  "Id": ,
  "Name": "Ocean Coral",
  "Address": "Trelawny, Jamaica",
  "Rating": 4.5,
  "CountryId": 1
}


###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
Content-Type: {{json}}

{
  "email": "user1@localhost.com",
  "password": "Password1!",
  "firstName": "John",
  "lastName": "Doe"
}

###
POST {{HotelListing.Api_HostAddress}}/api/auth/login
//Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  "email": "admin1@localhost.com",
  "password": "Password1!"
}

###

POST {{HotelListing.Api_HostAddress}}/api/auth/register
#Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  "email": "admin1@localhost.com",
  "password": "Password1!",
  "firstName": "John",
  "lastName": "Doe",
  "role": "Administrator"
}



###

GET {{HotelListing.Api_HostAddress}}/api/apikey
X-Api-Key: {{apiKey}}

###

GET {{HotelListing.Api_HostAddress}}/api/basicauth
Authorization: Basic {{apiKey}}

###
